### ISSUE TITLE
consolidate populating AWS env vars in utils repo

### ISSUE THREAD

**Issue by filmaj** [architect/utils#8]
The goal in this issue is to get a project-wide idea of where and how AWS credentials are needed and used, and consolidate setting and leveraging these creds in a consistent way across the project by DRYing up the code and storing it in one place in the utils package.

# TODO

- [ ] figure out where AWS env vars / credentials are set and used project-wide
- [ ] consolidate in the utils repo
- [ ] update all submodule repos to use single utils method
- [ ] get info from brian why empty shared creds object is set in cli

**Comment by filmaj** [comment]
@brianleroux whenever you are back, would you be able to share what the thinking is behind this code in cli (https://github.com/architect/cli/blob/master/src/before/01-ensure-creds.js#L45-L50)? It breaks some shit inside sandbox (see https://github.com/architect/sandbox/issues/24), which is the impetus behind this issue.

**Comment by ryanblock** [comment]
Chatted with Brian today about this issue, will retire the ensure creds file and specify a means of loading/not loading the actual credentials for the various callers of the `populate-aws` util.

**Comment by ryanblock** [comment]
As of 1.2.7 I think we'll start to have a path forward with the new [`utils.initAWS()`](https://github.com/architect/utils/blob/master/init-aws.js)
